### ISSUE TITLE
Famous db_nmap issue

### ISSUE THREAD

**Issue by Toontje** [rsmudge/armitage#187]
I have the famous db_nmap issue where i can run db_nmap perfectly well from msfconsole, but in armitage it fails. Any ideas how to fix this?
OSX 10.10
Metasploit is at the latest version.
Armitage is at the latest downloadable version. So not compiled from source.
Armitage launched with /Applications/Armitage.app/Contents/MacOS/JavaAppLauncher -E

```
msf > db_nmap --min-hostgroup 96 -T4 -A -v -n 172.17.1.1
[-] Error while running command db_nmap: Broken pipe

Call stack:
/opt/metasploit-framework/embedded/lib/ruby/2.1.0/open3.rb:193:in `spawn'
/opt/metasploit-framework/embedded/lib/ruby/2.1.0/open3.rb:193:in `popen_run'
/opt/metasploit-framework/embedded/lib/ruby/2.1.0/open3.rb:93:in `popen3'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:1862:in `block in cmd_db_nmap'
/opt/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:1822:in `cmd_db_nmap'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:203:in `run'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/web/console.rb:71:in `block in initialize'
/opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:100:in `call'
/opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
```

**Comment by felangga** [comment]
I still have this error on Sierra 10.12, how to resolve this issue ?

**Comment by Aspect9** [comment]
i just installed linux for like the 4th time specifically for Armitage. Now its got a "broken Pipe" fok
