### ISSUE TITLE
Somthing went wrong:console.allocate

### ISSUE THREAD

**Issue by kingxiaofire** [rsmudge/armitage#219]
Somthing went wrong:
console.allocate
Error:
java.lang.RuntimeException:undefined methed 'migratef' for #<Metasploit::Framework::DataService::RemoteHTTPDataService:0x00007fe4ff330220>

How can I solve this problem?
while l run armitage on macos 10.12.6
metasploit5,    java version "1.8.0_181", postgres (PostgreSQL) 11.1
Thanks!

**Comment by dzxs** [comment]
> Somthing went wrong:
> console.allocate
> Error:
> java.lang.RuntimeException:undefined methed 'migratef' for #Metasploit::Framework::DataService::RemoteHTTPDataService:0x00007fe4ff330220
> 
> How can I solve this problem?
> while l run armitage on macos 10.12.6
> metasploit5, java version "1.8.0_181", postgres (PostgreSQL) 11.1
> Thanks!

`msfdb reinit`

**Comment by kingxiaofire** [comment]
I'm sorry this didn't work out. Could you tell me the reason for the mistake?

**Comment by C0D3-M4513R** [comment]
I'm getting this, when I run armitage via console. 
`msfdb reinit` works at first but breaks after a second start.

```
[-] Metasploit Framework Exception: undefined method `migrated' for #<Metasploit::Framework::DataService::RemoteHTTPDataService:0x00007fa5fd698548>
[lib/metasploit/framework/data_service/proxy/core.rb:136:in `method_missing', lib/msf/ui/web/console.rb:52:in `initialize', lib/msf/ui/web/driver.rb:67:in `new', lib/msf/ui/web/driver.rb:67:in `create_console', lib/msf/core/rpc/v10/rpc_console.rb:29:in `rpc_create', lib/msf/core/rpc/v10/service.rb:153:in `block in process', lib/ruby/2.5.0/timeout.rb:93:in `block in timeout', lib/ruby/2.5.0/timeout.rb:33:in `block in catch', lib/ruby/2.5.0/timeout.rb:33:in `catch', lib/ruby/2.5.0/timeout.rb:33:in `catch', lib/ruby/2.5.0/timeout.rb:108:in `timeout', lib/msf/core/rpc/v10/service.rb:153:in `process', lib/msf/core/rpc/v10/service.rb:91:in `on_request_uri', lib/msf/core/rpc/v10/service.rb:72:in `block in start', lib/rex/proto/http/handler/proc.rb:38:in `on_request', lib/rex/proto/http/server.rb:368:in `dispatch_request', lib/rex/proto/http/server.rb:302:in `on_client_data', lib/rex/proto/http/server.rb:161:in `block in start', lib/rex/io/stream_server.rb:48:in `on_client_data', lib/rex/io/stream_server.rb:199:in `block in monitor_clients', lib/rex/io/stream_server.rb:197:in `each', lib/rex/io/stream_server.rb:197:in `monitor_clients', lib/rex/io/stream_server.rb:73:in `block in start', lib/rex/thread_factory.rb:22:in `block in spawn', lib/msf/core/thread_manager.rb:106:in `block in spawn']

```
